plugins {
    id 'java'
    id 'fabric-loom' version '1.14-SNAPSHOT'
}

base {
    archivesName = "$archives_name-$project.name"
}

loom {
    runs {
        gametest {
            server()
            name "Game Test"
            source sourceSets.main
            vmArg "-Dfabric-api.gametest"
            vmArg "-Dfabric-api.gametest.report-file=${layout.buildDirectory.get()}/junit.xml"
            runDir "build/gametest"
        }
    }
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

configurations {
    fatJar {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.officialMojangMappings()

    fatJar implementation(files(project(':common').tasks.jar))
    api project(':common')
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
}

processResources {
    from project(':common').tasks.processResources

    replaceProperties.compute('authors', (key, val) ->
        (val as String).split(',').collect(str -> '"' + str.trim() + '"'))

    replaceProperties['fabric_loader_version'] = fabric_loader_version

    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.fatJar.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}