plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'java'
}

repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.officialMojangMappings()

    compileOnly "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
}

base {
    archivesName = "$archives_name-$project.name"
}

java {
    withSourcesJar()
}

jar {
    manifest {
        attributes.put('FMLModType', 'GAMELIBRARY')
        attributes.put('Automatic-Module-Name', 'deermodcommon')
    }
}